times = ('botafogo', 'palmeira','flamengo','internacional','fortaleza','são paulo', 'corinthians','bahia','cruzeiro','vasco da gama')
print('-='*15)
print(times[0:5])
print('-='*15)
print(times[-4:])
print('-='*15)
print(sorted(times))
print('-='*15)
print(f'o flamengo esta na posição {times.index("flamengo")+1}°')